name: Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

   build:

    strategy:
      matrix:
        configuration: [Release]
        platform: [x64]

    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
      - name: Publish for Windows x64
        run: dotnet publish -r win-x64 -c Release
      - name: Publish for Windows ARM64
        run: dotnet publish -r win-arm64 -c Release
      - name: Publish for macOS x64
        run: dotnet publish -r osx-x64 -c Release
      - name: Publish for macOS ARM64
        run: dotnet publish -r osx-arm64 -c Release
      - name: Publish for Linux x64
        run: dotnet publish -r linux-x64 -c Release
      - name: Publish for Linux ARM64
        run: dotnet publish -r linux-arm64 -c Release
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: RetroGPT
          path: |
            bin/Release/net7.0/win-x64/publish
            bin/Release/net7.0/win-arm64/publish
            bin/Release/net7.0/osx-x64/publish
            bin/Release/net7.0/osx-arm64/publish
            bin/Release/net7.0/linux-x64/publish
            bin/Release/net7.0/linux-arm64/publish